project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r"^", include("tk.urls", namespace="tk")),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tk/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.base import TemplateView

from django.contrib.auth.views import login as login_view, logout as logout_view

from .views import *

urlpatterns = patterns('',
    url(r'^$', index_view, name="index", ),
    url(r'^add-activity/$', add_activity_view, name="add_activity", ),
    url(r'^action/activity-(?P<activity_pk>\d+)/start/$', action_start_process, name="action_start", ),
    url(r'^action/activity-(?P<activity_pk>\d+)/stop/$', action_stop_process, name="action_stop", ),
    url(r'^action/activity-(?P<activity_pk>\d+)/delete/$', action_activity_delete_process, name="action_activity_delete", ),
    url(r'^action/time-part-(?P<time_part_pk>\d+)/delete/$', action_time_part_delete_process, name="action_time_part_delete", ),

    url(r'^activity-(?P<activity_pk>\d+)/delete/$', action_activity_delete_view, name="activity_delete", ),
    url(r'^time-part-(?P<time_part_pk>\d+)/delete/$', action_time_part_delete_view, name="time_part_delete", ),

    url(r'^export/activity-(?P<activity_pk>\d+).txt$', export_txt_view, name="export-txt", ),

    url(r'^activity-(?P<activity_pk>\d+)/detail/$', detail_view, name="detail", ),
    url(r'^activity-(?P<activity_pk>\d+)/settings/$', activity_settings_view, name="activity_settings", ),
    url(r'^activity-(?P<time_part_pk>\d+)/edit-note/$', edit_note_view, name="edit_note", ),

    url(r'^settings/$', settings_view, name="settings", ),
    url(r'^change-password/$', change_password_view, name="change_password", ),
    url(r'^change-password/done/$', TemplateView.as_view(template_name="tk/change_password_done.html"), name="change_password_done", ),

    url(r'^login/$', login_view, name="login", ),
    url(r'^logout/$', logout_view, name="logout", ),
)

tk/forms.py
from django import forms

from .models import Activity, TimePart, Profile


class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ("name", "watchers")

class TimePartForm(forms.ModelForm):
    start_dt = forms.DateTimeField(label="start")
    stop_dt = forms.DateTimeField(label="stop", required=False)

    class Meta:
        model = TimePart
        fields = ("note", )

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput(render_value=True))

class SettingsForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ("deleted", "user",)

tk/views.py
import time
import datetime

from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, HttpResponseBadRequest
from django.template import RequestContext
from django.core.urlresolvers import reverse

from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .models import Activity, TimePart
from .forms import ActivityForm, TimePartForm, LoginForm, SettingsForm
from .helpers import time2str, date2time


@login_required
def index_view(request, template="tk/index.html"):
    activities = Activity.objects.active().filter(Q(owner=request.user.profile) | Q(watchers=request.user.profile))

    today = datetime.datetime.now()
    this_month_first_day = datetime.date(day=1, month=today.month, year=today.year)
    last_month_last_day = this_month_first_day - datetime.timedelta(days=1)
    last_month_first_day = datetime.date(year=last_month_last_day.year, month=last_month_last_day.month, day=1)

    return render_to_response(template,
        {
            "Activity": Activity,

            "activities": activities,
            'last_month_start': int(date2time(last_month_first_day)),
            'last_month_stop': int(date2time(last_month_last_day)),
        },
        context_instance=RequestContext(request))

@login_required
def add_activity_view(request, template="tk/add_activity.html"):
    add_activity_form = ActivityForm(request.POST or None)

    if add_activity_form.is_valid():
        obj = add_activity_form.save(commit=False)
        obj.owner = request.user.profile
        obj.save()
        for watcher in add_activity_form.cleaned_data["watchers"]:
            obj.watchers.add(watcher)
        obj.save()
        return HttpResponseRedirect("/")

    return render_to_response(template,
        {
            "add_activity_form": add_activity_form,
        },
        context_instance=RequestContext(request))

@login_required
def activity_settings_view(request, activity_pk, template="tk/activity_settings.html"):
    activity = get_object_or_404(Activity, pk=activity_pk)
    if activity.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    activity_settings_form = ActivityForm(request.POST or None, instance=activity)

    if activity_settings_form.is_valid():
        activity_settings_form.save()
        return HttpResponseRedirect(reverse("tk:detail", args=(activity.pk, )))

    return render_to_response(template,
        {
            "activity": activity,

            "activity_settings_form": activity_settings_form,
        },
        context_instance=RequestContext(request))

@login_required
def action_start_process(request, activity_pk):
    activity = get_object_or_404(Activity, pk=activity_pk)
    if activity.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")


    if activity.timepart_set.all() and not activity.get_last_timepart().stop:
        return HttpResponseBadRequest("400 Already started")

    time_part = TimePart(activity=activity)
    time_part.start = time.time()
    time_part.save()
    return HttpResponseRedirect(request.GET.get("next", "/"))

@login_required
def action_stop_process(request, activity_pk):
    activity = get_object_or_404(Activity, pk=activity_pk)
    if activity.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    if not activity.timepart_set.all() and activity.get_last_timepart().stop:
        return HttpResponseBadRequest("400 Already stopped")

    time_part = activity.get_last_timepart()
    time_part.stop = time.time()
    time_part.save()
    return HttpResponseRedirect(request.GET.get("next", "/"))

@login_required
def action_activity_delete_view(request, activity_pk, template="tk/activity_delete.html"):
    activity = get_object_or_404(Activity, pk=activity_pk)
    if activity.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    return render_to_response(template,
    {
        "activity": activity,
    },
    context_instance=RequestContext(request))

@login_required
def action_time_part_delete_view(request, time_part_pk, template="tk/time_part_delete.html"):
    time_part = get_object_or_404(TimePart, pk=time_part_pk)
    if time_part.activity.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    return render_to_response(template,
    {
        "time_part": time_part,
    },
    context_instance=RequestContext(request))

@login_required
def action_activity_delete_process(request, activity_pk):
    activity = get_object_or_404(Activity, pk=activity_pk)
    if activity.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    activity.deleted = True
    activity.save()
    return HttpResponseRedirect(request.GET.get("next", "/"))

@login_required
def action_time_part_delete_process(request, time_part_pk):
    time_part = get_object_or_404(TimePart, pk=time_part_pk)
    if time_part.activity.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    time_part.deleted = True
    time_part.save()
    return HttpResponseRedirect(reverse("tk:detail", args=(time_part.activity.pk, )))

@login_required
def detail_view(request, activity_pk, template="tk/detail.html"):
    activity = get_object_or_404(Activity, pk=activity_pk)
    if activity.owner != request.user.profile and request.user.profile not in activity.watchers.active():
        return HttpResponseForbidden("403 Forbidden")

    return render_to_response(template,
        {
            "Activity": Activity,

            "activity": activity,
            "time_parts": activity.timepart_set.active(),
        },
        context_instance=RequestContext(request))

@login_required
def change_password_view(request, template="tk/change_password.html"):
    from django.contrib.auth.forms import PasswordChangeForm


    change_password_form = PasswordChangeForm(data=request.POST or None, user=request.user)
    if change_password_form.is_valid():
        change_password_form.save()
        return HttpResponseRedirect(reverse("tk:change_password_done"))
    return render_to_response(template,
        {
            "change_password_form": change_password_form,
        },
        context_instance=RequestContext(request))

@login_required
def edit_note_view(request, time_part_pk, template="tk/time_part.html"):
    time_part = get_object_or_404(TimePart, pk=time_part_pk)
    if time_part.activity.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    time_part_form = TimePartForm(request.POST or None, instance=time_part)
    time_part_form.fields["start_dt"].initial = datetime.datetime.fromtimestamp(time_part.start)
    if time_part.stop:
        time_part_form.fields["stop_dt"].initial = datetime.datetime.fromtimestamp(time_part.stop)
    if time_part_form.is_valid():
        obj = time_part_form.save(commit=False)
        obj.start = time.mktime(time_part_form.cleaned_data["start_dt"].timetuple())
        if obj.stop:
            if time_part_form.cleaned_data["stop_dt"]:
                obj.stop = time.mktime(time_part_form.cleaned_data["stop_dt"].timetuple())
            else:
                obj.stop = None
        obj.save()
        return HttpResponseRedirect(reverse("tk:detail", args=(time_part.activity.pk, )))

    return render_to_response(template,
        {
            "activity": time_part.activity,

            "time_part_form": time_part_form,
        },
        context_instance=RequestContext(request))

@login_required
def settings_view(request, template="tk/settings.html"):
    settings_form = SettingsForm(request.POST or None, instance=request.user.profile)
    if settings_form.is_valid():
        settings_form.save()
        return HttpResponseRedirect("")

    return render_to_response(template,
        {
            "settings_form": settings_form,
        },
        context_instance=RequestContext(request))

@login_required
def export_txt_view(request, activity_pk, template="tk/activity_export.txt"):
    activity = get_object_or_404(Activity, pk=activity_pk)
    if activity.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    try:
        start = int(request.GET.get('start'))
        stop = int(request.GET.get('stop'))

        if stop - start > 3600*24*366:
            return HttpResponseForbidden('403 Forbidden')
    except TypeError:
        return HttpResponseBadRequest('400 Bad Request')

    days = []
    days_sum = 0
    day = datetime.date.fromtimestamp(start)
    while True:
        print day
        day_sum = activity.get_day_sum(day)
        if day_sum:
            days.append({
                "day": day,
                "sum": time2str(day_sum),
            })
        days_sum += day_sum
        day = day + datetime.timedelta(days=1)
        if date2time(day) > stop:
             break
    return render_to_response(template,
    {
        "days": days,
        "activity": activity,
        "total": time2str(days_sum),
    },
    context_instance=RequestContext(request), content_type="text/plain")

tk/templates/tk/activity_delete.html
{% extends "base.html"%}
{% block content %}
<h2>{{activity}} / delete</h2>
<a href="{% url 'tk:action_activity_delete' activity.pk %}">yes</a>
<br><br>
<a href="{% url 'tk:detail' activity.pk %}">no</a>
{% endblock content %}

tk/templates/tk/activity_settings.html
{% extends "base.html"%}
{% block content %}
<h2>{{activity}} / settings</h2>
<form action="{{request.path}}" method="post">
{% csrf_token %}
{{activity_settings_form.as_p}}
<input type="submit" value="save">
</form>
{% endblock content %}

tk/templates/tk/add_activity.html
{% extends "base.html"%}
{% block content %}
<h2>add activity</h2>
<form action="{{request.path}}" method="post">
{% csrf_token %}
{{add_activity_form.as_p}}
<input type="submit" value="add">
</form>
{% endblock content %}

tk/templates/tk/change_password.html
{% extends "base.html"%}
{% block content %}
<h2>change password</h2>
<form action="{{request.path}}" method="post">
{% csrf_token %}
{{change_password_form.as_p}}
<input type="submit" value="change">
</form>
{% endblock content %}

tk/templates/tk/change_password_done.html
{% extends "base.html"%}
{% block content %}
<h2>change password done</h2>
{% endblock content %}

tk/templates/tk/detail.html
{% extends "base.html"%}
{% block content %}
<h2>{{activity}}{% if activity.owner != request.user.profile %} (watching){% endif %}</h2>

{% if activity.owner == request.user.profile %}
    {% if activity.get_next_action == Activity.NEXT_ACTION_START %}
        <a href="{% url 'tk:action_start' activity.pk %}?next={{request.path}}">start</a>
    {% elif activity.get_next_action == Activity.NEXT_ACTION_STOP %}
        <a href="{% url 'tk:action_stop' activity.pk %}?next={{request.path}}">stop</a>
    {% endif %}
    <a href="{% url 'tk:activity_settings' activity.pk %}">settings</a>
    <a href="{% url 'tk:activity_delete' activity.pk %}">delete</a>
{% endif %}

<table>
    <tr>
        <td>total</td>
        <td>{{activity.total_str}}</td>
    </tr>
    <tr>
        <td>today</td>
        <td>{{activity.today_str}}</td>
    </tr>
    <tr>
        <td>this week</td>
        <td>{{activity.this_week_str}}</td>
    </tr>
    <tr>
        <td>this month</td>
        <td>{{activity.this_month_str}}</td>
    </tr>
    <tr>
        <td>last day</td>
        <td>{{activity.last_day_str}}</td>
    </tr>
    <tr>
        <td>last week</td>
        <td>{{activity.last_week_str}}</td>
    </tr>
    <tr>
        <td>last month</td>
        <td>{{activity.last_month_str}}</td>
    </tr>
</table>

<table>
    <tr>
        <td>total</td>
        <td>start</td>
        <td>stop</td>
        <td>note</td>
        <td></td>
        <td></td>
    </tr>
    {% for time_part in time_parts %}
        <tr>
            <td>{{time_part.time_str}}</td>
            <td>{{time_part.start_dt|date:"H:i:s d/m/y"}}</td>
            <td>
                {% if time_part.stop %}
                    {{time_part.stop_dt|date:"H:i:s d/m/y"}}
                {% endif %}
            </td>
            <td>{{time_part.note}}</td>
            <td>
                {% if activity.owner == request.user.profile %}
                    <a href="{% url "tk:edit_note" time_part.pk %}">edit</a>
                {% endif %}
            </td>
            <td>
                {% if activity.owner == request.user.profile %}
                    <a href="{% url 'tk:time_part_delete' time_part.pk %}">delete</a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock content %}

tk/templates/tk/index.html
{% extends "base.html"%}
{% block content %}
<table>
    <tr>
        <td>activity</td>
        <td>start/stop</td>
        <td>total</td>
        <td>today</td>
        <td>this week</td>
        <td>this month</td>
        <td>last day</td>
        <td>last week</td>
        <td>last month</td>
        <td></td>
    </tr>
    {% for activity in activities %}
        <tr>
            <td>
                <a href="{% url 'tk:detail' activity.pk %}">{{activity}}</a>
                {% if activity.owner != request.user.profile %}(watching){% endif %}
            </td>
            <td>
                {% if activity.owner == request.user.profile %}
                    {% if activity.get_next_action == Activity.NEXT_ACTION_START %}
                        <a href="{% url 'tk:action_start' activity.pk %}">start</a>
                    {% elif activity.get_next_action == Activity.NEXT_ACTION_STOP %}
                        <a href="{% url 'tk:action_stop' activity.pk %}">stop</a>
                    {% endif %}
                {% endif %}
            </td>
            <td>{{activity.total_str}}</td>
            <td>{{activity.today_str}}</td>
            <td>{{activity.this_week_str}}</td>
            <td>{{activity.this_month_str}}</td>
            <td>{{activity.last_day_str}}</td>
            <td>{{activity.last_week_str}}</td>
            <td>{{activity.last_month_str}}</td>
            <td><a href="{% url 'tk:export-txt' activity.pk %}?start={{last_month_start}}&stop={{last_month_stop}}" target="_blank">export txt</a></td>
        </tr>
    {% endfor %}
</table>
{% endblock content %}

tk/templates/tk/settings.html
{% extends "base.html"%}
{% block content %}
<h2>global settings</h2>
<a href="{% url "tk:change_password" %}">change password</a>
<form action="{{request.path}}" method="post">
{% csrf_token %}
{{settings_form.as_p}}
<input type="submit" value="save">
</form>
{% endblock content %}

tk/templates/tk/time_part.html
{% extends "base.html"%}
{% block content %}
<h2>{{activity}} / time part</h2>
<form action="{{request.path}}" method="post">
{% csrf_token %}
{{time_part_form.as_p}}
<input type="submit" value="save">
</form>
{% endblock content %}

tk/templates/tk/time_part_delete.html
{% extends "base.html"%}
{% block content %}
<h2>{{time_part.activity}} / {{time_part.pk}} / delete</h2>
<a href="{% url 'tk:action_time_part_delete' time_part.pk %}">yes</a>
<br><br>
<a href="{% url 'tk:detail' time_part.activity.pk %}">no</a>
{% endblock content %}